name = input("enter your name: ")
#length = len(name)
#print(length)
#uppercase = name.upper()
#print(uppercase)
#print(name.lower())
#print(name.isdigit())
#print(name.count("a"))
#print(name.replace("a", "f"))
